name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -mod=readonly -v -race ./...

      - name: Test without cgo
        env:
          CGO_ENABLED: 0
        run: go test -mod=readonly -v ./...

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD -w -G'(^[^# /])|(^#\w)|(^\s+[^#/])' # Ignore whitespace and comments
